// additional root layout
// actualy this app can work fine without this file,
// but redirect not work if the redirect target has different root layout
// it need this root layout

import { Inter } from "next/font/google";
import "./css/globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <>
            <head>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.6.0/css/all.min.css" />
            </head>
            <html>
                <body>
                    {children}
                </body>
            </html>
        </>
    );
}